[book]
authors = ["e-Yantra"]
language = "en"
multilingual = false
src = "src"
title = "eYRC 2021-22: Soil Monitoring Bot (SM)"

[build]
build-dir = "sm_theme"
create-missing = false

[output.html.fold]
enable = true
level = 0

[output.html.print]
enable = false

#[output.html.playground]
#editable = true
#copyable = true
#copy-js = true
#line-numbers = true

[output.html]
theme = "new_mdbook_theme"
default-theme = "rust"
no-section-label = true
google-analytics = "UA-145861739-2"
#additional-css = ["style.css"]
#additional-js = ["sidebar.js"]
#input-404 = "404.html"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.links]
[preprocessor.index]
